# Generated by Django 5.0 on 2023-12-07 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectivity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="connectivity.country"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="connectivity.city"
            ),
        ),
        migrations.AlterField(
            model_name="street",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="connectivity.district"
            ),
        ),
    ]
