# Generated by Django 5.0 on 2023-12-09 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectivity", "0002_alter_city_country_alter_district_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CriminalCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField()),
                ("name", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("place_of_residence", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CriminalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=1000, null=True)),
                (
                    "criminal_code_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connectivity.criminalcode",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connectivity.profile",
                    ),
                ),
            ],
        ),
    ]
