# Generated by Django 5.0 on 2023-12-09 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectivity", "0003_criminalcode_profile_criminalrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_immediate", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=1000)),
                (
                    "from_camera_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="connectivity.camera",
                    ),
                ),
                ("profile_ids", models.ManyToManyField(to="connectivity.profile")),
            ],
        ),
    ]
